<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-FHVIN2VS" name="com.qa.hubspot.tests.LoginPageTest" tests="6" failures="0" timestamp="27 Jul 2020 20:19:39 GMT" time="135.653" errors="1">
  <testcase name="verifySignUpLinkTest" time="36.125" classname="com.qa.hubspot.tests.LoginPageTest"/>
  <testcase name="verifySignUpLinkTest" time="14.477" classname="com.qa.hubspot.tests.LoginPageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.hubspot.utils.ElementUtil.doIsDisplayed(ElementUtil.java:55)
at com.qa.hubspot.pages.LoginPage.isSignUpLinkExists(LoginPage.java:41)
at com.qa.hubspot.tests.LoginPageTest.verifySignUpLinkTest(LoginPageTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifySignUpLinkTest -->
  <testcase name="verifyLoginPageTitleTest" time="1.874" classname="com.qa.hubspot.tests.LoginPageTest"/>
  <testcase name="verifyLoginPageTitleTest" time="4.231" classname="com.qa.hubspot.tests.LoginPageTest"/>
  <testcase name="loginTest" time="49.728" classname="com.qa.hubspot.tests.LoginPageTest"/>
  <testcase name="loginTest" time="29.218" classname="com.qa.hubspot.tests.LoginPageTest"/>
</testsuite> <!-- com.qa.hubspot.tests.LoginPageTest -->
